version: '3.4'

services:
  backend:
    build:
      context: ${PWD}/backend
      dockerfile: Dockerfile
    image: "udasocialblogging/backend"
    env_file:
      - ${PWD}/backend/uda-social-blogging.env
    ports:
      # http:
      - "51080:80"
      # https:
      - "51443:443"
    volumes:
      # remove the following for production with Dockerfile ADD
      - ${PWD}/backend/data:/app/data
      - ${PWD}/backend/application:/app/application
      - ${PWD}/backend/migrations:/app/migrations
      - ${PWD}/backend/tests:/app/tests
      - ${PWD}/backend/config.py:/app/config.py
      - ${PWD}/backend/app.py:/app/app.py
      - ${PWD}/backend/requirements.txt:/app/requirements.txt
      - ${PWD}/backend/uwsgi.ini:/app/uwsgi.ini  
      - ${PWD}/backend/start.sh:/app/start.sh      
    depends_on:
      - db
      - adminer

  db:
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=udacity
      - POSTGRES_PASSWORD=udacity
      - POSTGRES_DB=udasocialbloggingapp
    volumes:
      - ${PWD}/volume:/var/lib/postgresql/data

  adminer:
    image: "adminer"
    restart: always
    ports:
      - "58080:8080"
    depends_on:
      - db